language: generic 
sudo: required

services:
    - docker

before_install:
    - docker build -t aviguria/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true aviguria/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-west-3"
    app: "docker"
    env: "docker-env"
    bucket_name: "elasticbeanstalk-eu-west-3-561107956813"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY